# my global config
global:
  scrape_interval:     120s # By default, scrape targets every 15 seconds.
  evaluation_interval: 120s # By default, scrape targets every 15 seconds.

  external_labels:
      monitor: 'Infra'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
                - IP:9093
      scheme: http
      timeout: 10s

rule_files:
  - "/alertmanager/alert.rules/alerts.rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 120s
    metrics_path: /metrics
    static_configs:
            - targets: ['IP:9090','node-exporter:9100']

  - job_name: 'NAME'
    scheme: https
    basic_auth:
      username: ''
      password: ''
    metrics_path: /metrics
    static_configs:
      - targets: ['IP:']
  
